name: edubridge
description: Une application éducative pour connecter les enseignants et les étudiants.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  intl: ^0.18.1
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # Commenté les assets qui n'existent pas encore
  # assets:
  #   - assets/images/
  #   - assets/icons/

