// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9n_4NkxohrMQjib7yj1r9Xk-a2RgeToU',
    appId: '1:447755505970:web:55a5b595283d828963072b',
    messagingSenderId: '447755505970',
    projectId: 'edubridge-e0d97',
    authDomain: 'edubridge-e0d97.firebaseapp.com',
    storageBucket: 'edubridge-e0d97.firebasestorage.app',
    measurementId: 'G-D6S5XKPJZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCggVrXqbMjqL1qivFgT2SbKoqm7mysLsM',
    appId: '1:447755505970:android:e68dd59edb30a88063072b',
    messagingSenderId: '447755505970',
    projectId: 'edubridge-e0d97',
    storageBucket: 'edubridge-e0d97.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBA6pqYtzUlrglBEmD61f5jWJKzx6gO50',
    appId: '1:447755505970:ios:4bfefeb9f49f127c63072b',
    messagingSenderId: '447755505970',
    projectId: 'edubridge-e0d97',
    storageBucket: 'edubridge-e0d97.firebasestorage.app',
    iosBundleId: 'com.example.edubridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBA6pqYtzUlrglBEmD61f5jWJKzx6gO50',
    appId: '1:447755505970:ios:4bfefeb9f49f127c63072b',
    messagingSenderId: '447755505970',
    projectId: 'edubridge-e0d97',
    storageBucket: 'edubridge-e0d97.firebasestorage.app',
    iosBundleId: 'com.example.edubridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9n_4NkxohrMQjib7yj1r9Xk-a2RgeToU',
    appId: '1:447755505970:web:55a5b595283d828963072b',
    messagingSenderId: '447755505970',
    projectId: 'edubridge-e0d97',
    authDomain: 'edubridge-e0d97.firebaseapp.com',
    storageBucket: 'edubridge-e0d97.firebasestorage.app',
    measurementId: 'G-D6S5XKPJZN',
  );
}
